name: Run Unit Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install build dependencies and setuptools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python3-dev
          pip install --upgrade setuptools

      - name: Build C extension
        run: python3 python/setup.py build_ext --inplace

      - name: Run unit tests
        run: python3 -m unittest discover -v -s python/tests
