name: Run Unit Tests

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install build dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential python3-dev

      - name: Install pip and setuptools
        run: python3 -m pip install --upgrade pip setuptools

      - name: Build C extension
        run: python3 python/setup.py build_ext --inplace

      - name: Run unit tests
        run: python3 -m unittest discover -v -s python/tests
